const { GoogleGenAI } = require("@google/genai");

// Assumes process.env.GEMINI_API_KEY is set
// Ensure we use a realistic initialization that won't crash if key is missing during local scaffolding.
const key = process.env.GEMINI_API_KEY;
const ai = (key && key !== 'your_gemini_api_key_here') ? new GoogleGenAI({ apiKey: key }) : null;

async function getStylistFeedback(imageInput) {
  if (!ai) {
    return {
       rating: "8/10",
       suggestions: "This is a placeholder suggestion! To get real AI analysis, you critically need to paste a free Gemini API Key into the backend .env file. A sleek belt and some dark boots would look amazing here."
    };
  }

  try {
    let base64Data;
    let mimeType = "image/jpeg";
    if (imageInput.startsWith('http')) {
        const fetchRes = await fetch(imageInput);
        mimeType = fetchRes.headers.get('content-type') || "image/jpeg";
        const arrayBuffer = await fetchRes.arrayBuffer();
        base64Data = Buffer.from(arrayBuffer).toString('base64');
    } else {
        if (imageInput.includes(';base64,')) {
           mimeType = imageInput.split(';')[0].split(':')[1] || "image/jpeg";
        }
        base64Data = imageInput.includes(',') ? imageInput.split(',')[1] : imageInput;
    }
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: [
            "You are an expert fashion stylist. Look at this outfit. Rate it out of 10, and provide 2-3 short, concrete suggestions to improve or accessorize the look.",
            {
               inlineData: {
                   data: base64Data,
                   mimeType: mimeType
               }
            }
        ]
    });
    
    // Simple parsing assumption
    return {
        rating: "Generated by Gemini",
        suggestions: response.text
    };

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw new Error('Failed to get stylist feedback from Gemini.');
  }
}

module.exports = { getStylistFeedback };
